# /apps/blog.silarhi.fr/docker-compose.yml
services:

  database:
    image: mariadb:10.6
    container_name: "${NAME}_db"
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USERNAME}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_PASSWORD}"
    networks:
      - lan
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}-bdd.entryPoints=websecure
      - "traefik.http.services.${NAME}-bdd.loadbalancer.server.port=3001"
      - traefik.http.routers.${NAME}-bdd.rule=Host(`${NAME}.jrcan.dev`)
      - traefik.http.routers.${NAME}-bdd.tls=true
      - traefik.http.routers.${NAME}-bdd.tls.certresolver=myresolver


  app:
    container_name: ${NAME}
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
        - lan
        - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.${NAME}.entryPoints=websecure
      - "traefik.http.services.${NAME}.loadbalancer.server.port=3000"
      - traefik.http.routers.${NAME}.rule=Host(`${NAME}.jrcan.dev`)
      - traefik.http.routers.${NAME}.tls=true
      - traefik.http.routers.${NAME}.tls.certresolver=myresolver

    restart: always
    environment:
      # Application DB connection (read from .env)
      MARIADB_HOST: database
      MARIADB_PORT: "3306"
      MARIADB_USERNAME: "${MARIADB_USERNAME}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      container__name: ${NAME}
      database__client: mariadb
      database__connection__host: database
      database__connection__user: "${MARIADB_USERNAME}"
      database__connection__password: "${MARIADB_PASSWORD}"
      database__connection__database: "${MARIADB_DATABASE}"

networks:
  web:
    external: true
  lan:
    external: false
    name: lan_${NAME}


